---
title: "Ordinales"
author: "Martin Santamaria"
date: "17/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Datos Ordinales

```{r}
notas = ordered(c("S", "A", "N", "Ex", "S","S", "Ex", "Ex", "N", "A","A", "A", "A", "N", "S"),
                levels = c("S", "A", "N", "Ex"))
tn <- table(notas)
tn
```

```{r}
# set.seed(2018)
# clientes = sample(1:5, 50, replace = TRUE)
# clientes
# set.seed(NULL)

clientes = c(2,3,1,1,3,2,4,1,5,3,2,4,5,4,5,4,2,3,4,5,2,3,1,1,4,
             3,2,5,3,1,1,5,1,3,3,4,1,1,3,1,5,4,3,3,4,1,5,1,1,4)
l <-length(clientes)
t <- table(clientes)
t

# Frecuencias relativas globales
prop.table(t)

# Frecuencias acumuladas
cumsum(t)

# Frecuencias relativas acumuladas
cumsum(t) / l
cumsum(t / l)
cumsum(t) / sum(t)
cumsum(prop.table(t))

# No se puede
prop.table(cumsum(t))
prop.table(cumsum(tn))
```

```{r}
fa <- cumsum(tn)
fa
fra <- cumsum(prop.table(tn))
fra
```

```{r}
barplot(tn, main = "Diagrama de barras de frecuencias absolutas")
barplot(fa, main = "Diagrama de barras de frecuencias acumuladas")
```

```{r}
# Factor ordenado de notas
notas = ordered(c("S", "A", "N", "Ex", "S","S", "Ex", "Ex", "N", "A","A", "A", "A", "N", "S"),
                levels = c("S", "A", "N", "Ex"))

# Frecuencias absolutas de notas
tn <- table(notas)
tn

# Frecuencias acumuladas de notas
fa <- cumsum(tn)
fa

# Total de las frecuencias acumuladas
sum(fa)

# Frecuencias relativas globales (Con los valores obtenidos de las frecuencias acumuladas)
prop.table(fa)
```

```{r}
set.seed(2018)
longitud =  ordered(sample(c("Muy.Corto", "Corto", "Normal", "Largo", "Muy.Largo"), size = 100, replace = TRUE), levels = c("Muy.Corto", "Corto", "Normal", "Largo", "Muy.Largo"))
set.seed(NULL)
longitud

# Frecuencias Absolutas
Fr.Abs = table(longitud)
Fr.Abs

barplot(Fr.Abs, main = "Diagrama de frecuencias absolutas")

# Frecuencias Relativas
Fr.Rel = prop.table(Fr.Abs)
Fr.Rel

barplot(Fr.Rel, main = "Diagrama de frecuencias relativas")

# Frecuencias Absolutas Acumuladas
Fr.Acum = cumsum(Fr.Abs)
Fr.Acum

barplot(Fr.Acum, main = "Diagrama de frecuencias absolutas acumuladas")

# Frecuencias Relativas Acumuladas
Fr.RAcum = cumsum(Fr.Rel)
Fr.RAcum

barplot(Fr.RAcum, main = "Diagrama de frecuencias relativas acumuladas")
```

## Ordinales Multidimensionales

```{r fig.align='center'}
zonas = rep(c("A", "B", "C", "D"), c(30,25,35,10))
jirafas = data.frame(zonas, longitud)
str(jirafas)
head(jirafas)

tj <- table(zonas, longitud)
tj
str(tj)
head(tj)

apply(table(jirafas), MARGIN = 1, FUN = cumsum)
apply(tj, MARGIN = 1, FUN = cumsum)

apply(table(jirafas), MARGIN = 2, FUN = cumsum)

# Frecuencias Relativas Acumuladas
Fr.Acum.Jirafas <- apply(prop.table(table(jirafas), margin = 1), MARGIN = 1, FUN = cumsum)
t(Fr.Acum.Jirafas)

# Diagrama de barras
barplot(Fr.Acum.Jirafas,
        main = "Diagrama de barras de frecuencias\n relativadas acumuladas de longitudes por zonas",
        legend.text = TRUE,
        beside = TRUE,
        args.legend = list(
                            x = "topleft", 
                            cex = 0.55, 
                            title = "Longitud"
                          ))

```

## Cangrejos

```{r fig.align='center'}
crabs = read.table("../../../../../Data/datacrab.txt", header = TRUE)
crabs = crabs[,-1]
str(crabs)
head(crabs)

intervalos = cut(crabs$width, breaks = c(21,25,29,33,Inf), right = FALSE, 
                 labels = c("21-25", "25-29", "29-33", "33-..."))

crabs$width.rank = ordered(intervalos)
str(crabs)

table(crabs$width)

min(crabs$width)
max(crabs$width)
mean(crabs$width)

tabla = table(crabs[,c(1,6)])
tabla

tabla.Fr.Rel = round(prop.table(tabla, margin = 1),3)
tabla.Fr.Rel

tabla.Fr.Rel.Acum <- round(apply(prop.table(tabla, margin = 1), MARGIN = 1, FUN = cumsum), 3)
tabla.Fr.Rel.Acum
t(tabla.Fr.Rel.Acum)

# Gráficos

azul = c("cyan1", "cyan2", "cyan3", "cyan4")

barplot(t(tabla.Fr.Rel),
        ylim = c(0,1),
        beside = TRUE,
        legend.text = TRUE,
        col = azul,
        main = "Diagrama de barras de frecuencias relativas",
        args.legend = list(
                           x = "topright",
                           cex = 0.8
                          ))

naranja = c("darkorange1", "darkorange2", "darkorange3", "darkorange4")

barplot(tabla.Fr.Rel.Acum,
        ylim = c(0,1),
        beside = TRUE,
        legend.text = TRUE,
        col = naranja,
        main = "Diagrama de barras de frecuencias relativas acumuladas",
        args.legend = list(
                           x = "topleft",
                           cex = 0.5
                          ))
```
