---
title: "Distribución de Bernoulli"
author: "Martin Santamaria"
date: "16/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Función de densidad

$$f(k) = p^k(1-p)^{1-p}, \ k \in \{0,1\}$$

Sea $X = Be(p = 0.7)$, la distribución que modela la probabilidad de obtener una cara usando una moneda trucada. 

## En R

```{r}
library(Rlab)
dbern(0, prob = 0.7)
dbern(1, prob = 0.7)
```

```{r}
pbern(0, prob = 0.7)
pbern(1, prob = 0.7)
```

```{r}
qbern(0.5, prob = 0.7)
qbern(0.25, prob = 0.7)
qbern(0.75, prob = 0.7)
```

```{r}
data = rbern(100, prob = 0.7)
data
```

```{r}
hist(data)
```

## En `Python`

```{r}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
```

```{python}
from scipy.stats import bernoulli
import matplotlib.pyplot as plt

p = 0.7
mean, var, skew, kurt = bernoulli.stats(p, moments = 'mvsk')

print(f"Media {mean}")
print(f"Varianza {var}")
print(f"Sesgo {skew}")
print(f"Curtosis {kurt}")
```

```{python}
fix, ax = plt.subplots(1,1)
x = bernoulli.rvs(p, size = 1000)
ax.hist(x)
plt.show()
```
