---
title: "Binomial"
author: "Martin Santamaria"
date: "17/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sea $X = B(n = 30,\ p = 0.6)$

## Función de densidad

$$f(k) = {n \choose k} p^k (1-p)^{n-k} $$

## Función de distribución

$$F(x) = \left\{\begin{array}{cl} 
              0 & \text{si } x \lt 0 \\ 
              \sum_{k=0}^x f(k) & \text{si } 0 \le x \lt n \\
              1 & \text{si } x \ge n 
          \end{array}\right.$$
          
## En `R`

```{r}
library(Rlab)
n = 30
p = 0.6
plot(0:n, dbinom(0:n, size = n, prob = p))
plot(0:n, pbinom(0:n, size = n, prob = p))
qbinom(0.25, n, p)
qbinom(0.5, n, p)
qbinom(0.75, n, p)
hist(rbinom(100000, n, p), breaks = 0:n)
plot(0:n, dbinom(0:n, size = n, prob = p), type = 'l', col = "purple", lwd = 1.5)
hist(rbinom(100000, n, p), breaks = 0:n, freq = FALSE, add = TRUE)
```

## En `Python`

```{r}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
```

```{python}
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

fig, ax = plt.subplots(1,1)
n = 7
p = 0.4

mean, var, skew, kurt = binom.stats(n, p, moments = 'mvsk')

print(f"Media {mean}")
print(f"Varianza {var}")
print(f"Sesgo {skew}")
print(f"Curtosis {kurt}")

x = np.arange(binom.ppf(0.01,n,p), binom.ppf(0.9999,n,p) + 1)

ax.plot(x, binom.pmf(x,n,p), 'bo', ms = 8, label = "Función de densidad de B(7,0.4)")
ax.vlines(x, 0, binom.pmf(x,n,p), colors = 'b', lw = 4, alpha = 0.5)

rv = binom(n,p)

ax.vlines(x, 0, rv.pmf(x), colors = 'k', linestyle = '--', lw = 1, label = "Distribución teórica")
ax.legend(loc = 'best', frameon = False)

plt.show()
```

```{python}
fig, ax = plt.subplots(1,1)

ax.plot(x, binom.cdf(x,n,p), 'bo', ms = 8, label = "Función de densidad de B(7,0.4)")
ax.vlines(x, 0, binom.cdf(x,n,p), colors = 'b', lw = 4, alpha = 0.5)
```

```{python}
fig, ax = plt.subplots(1,1)

r = binom.rvs(n,p,size = 100000)

ax.hist(r, bins = np.arange(0,n+1), density = True)
ax.plot(x, binom.pmf(x,n,p))

plt.show()
```
