---
title: "Geométrica"
author: "Martin Santamaria"
date: "20/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Función de densidad

Sea $X = Geom(p = 0.1)$ la distribución que modela la probabilidad de intentar abrir una puerta hasta conseguirlo.

$$f(k) = (1 - p)^{k-1}p$$

## En `R`

```{r}
library(Rlab)
p = 0.1
plot(0:20, dgeom(0:20, p)) 
plot(0:20, pgeom(0:20, p), ylim = c(0,1)) 
qgeom(0.25, p)
qgeom(0.5, p)
qgeom(0.75, p)
plot(0:100, dgeom(0:100, p), type = 'l', col = "purple", lwd = 1.5)
hist(rgeom(100000, p), freq = FALSE, ylim = c(0,0.1), add = TRUE)
```

## En `Python`

```{r}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
```

```{python}
from scipy.stats import geom
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1,1)
p = 0.3
mean, var, skew, kurt = geom.stats(p, moments = 'mvsk')

print(f"Media {mean}")
print(f"Varianza {var}")
print(f"Sesgo {skew}")
print(f"Curtosis {kurt}")

x = np.arange(geom.ppf(0.01,p), geom.ppf(0.99,p))

ax.plot(x, geom.pmf(x, p), 'bo', ms = 8, label = "Función de probabilidad de Geom(0.3)")
ax.vlines(x, 0, geom.pmf(x, p), colors = 'b', lw = 4, alpha = 0.5)

rv = geom(p)

ax.vlines(x, 0, rv.pmf(x), colors = 'k', linestyles = '--', lw = 1, label = "Frozen PMF")
ax.legend(loc = 'best', frameon = False)

plt.show()
```

```{python}
fig, ax = plt.subplots(1,1)

prob = geom.cdf(x,p)
ax.plot(x, prob, 'bo', ms = 8, label = "Función de distribución acumulada de Geom(0.3)")

axes = fig.gca()
axes.set_ylim([0, 1.1])

plt.show()
```

```{python}
fig, ax = plt.subplots(1,1)

r = geom.rvs(p, size = 100000)
x = np.arange(geom.ppf(0.01,p), 25)

ax.hist(r, density = True)
ax.plot(x, geom.pmf(x, p))

ax.set_xlim(0, 25)
ax.set_ylim(0, 0.25)
ax.set_yticklabels(['', '0.05', '0.10', '0.15', '0.20', '0.25'])

plt.show()
```
