---
title: "Agrupados"
author: "Martin Santamaria"
date: "29/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Agrupados

```{r}
pesos = c(55.2,54.0,55.2,53.7,60.2,53.2,54.6,55.1,51.2,53.2,54.8,52.3,
          56.9,57.0,55.0,53.5,50.9,55.1,53.6,61.2,59.5,50.3,52.7,60.0)

barplot(table(pesos))
```

```{r}
crabs = read.table("../../../../../Data/datacrab.txt", header = TRUE)
str(crabs)
cw = crabs$width
n = length(cw)
```

## Número de clases

```{r}
# Regla de la raíz cuadrada
k_r = ceiling(sqrt(n))
k_r

# Regla de Sturges
k_st = ceiling(1 + log(n, 2))
k_st
nclass.Sturges(cw)

# Regla de Scott
As = 3.5 * sd(cw) * n^(-1/3)
k_sc = ceiling(diff(range(cw)) / As)
k_sc
nclass.scott(cw)

# Regla de Freedman-Diaconis
# Amplitud teórica
Afd = 2 * (quantile(cw, 0.75, names = FALSE) - quantile(cw, 0.25, names = FALSE)) * n^(-1/3)
k_fd = ceiling(diff(range(cw)) / Afd)
k_fd
nclass.FD(cw)
```

## Amplitud

```{r}
A = diff(range(cw)) / k_sc
A
A = 1.3
```

## Extremos de los intervalos

```{r}
L1 = min(cw) - 1/2 * 0.1 # Precisión
L1
```

```{r}
# L = c(L1)
# for(i in 2:(k_sc + 1)){
#   L[i] = L[i-1] + A
# }
# L
L = L1 + A * (0:k_sc)
L
```

## Marcas de clases

```{r}
X1 = (L[1] + L[2]) / 2
X1
```

```{r}
# X = X1 + A * (0:(k_sc - 1))
# X
X = (L[1:length(L)-1] + L[2:length(L)]) / 2
X
```
