---
title: "Clases"
author: "Martin Santamaria"
date: "1/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## La función `cut`

```{r}
iris_df = iris
petals = iris$Petal.Length
iris_df$div1 = cut(petals, breaks = 5, right = FALSE)
iris_df$div2 = cut(petals, breaks = ceiling(sqrt(length(petals))), right = FALSE)
iris_df$div3 = cut(petals, breaks = c(1,2,3,4,5,6,7), right = FALSE)
iris_df$div4 = cut(petals, breaks = 5, right = FALSE, labels = FALSE)
iris_df$div5 = cut(petals, breaks = 5, right = FALSE, labels = c("Peq", "Norm", "Gran", "XGran", "Gigan"))
iris_df
```

## Funciones para las tablas de frecuencias

```{r}
# Primera función
TablaFrecs = function(x,k,A,p){
  L = min(x) - p/2 + A * (0:k)
  x_cut = cut(x, breaks = L, right = FALSE)
  intervals = levels(x_cut)
  mc = (L[1] + L[2]) / 2 + A * (0:(k-1))
  Fr.abs = as.vector(table(x_cut))
  Fr.rel = round(Fr.abs / length(x) ,4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel) 
  tabla
}
```

```{r}
# Segunda función
TablaFrecs.L = function(x,L,V){
  x_cut = cut(x, breaks = L, right = FALSE, include.lowest = V)
  intervals = levels(x_cut)
  mc = (L[1:(length(L) - 1)] + L[2:length(L)]) / 2
  Fr.abs = as.vector(table(x_cut))
  Fr.rel = round(Fr.abs / length(x) ,4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel) 
  tabla
}
```

```{r}
# Aproximación de los cuantiles de los datos "reales"
quantile.aprox = function(tabla, L, pos.inf.ic, p = 0.5){
  n = tail(tabla$Fr.cum.abs, 1)
  Lp = L[pos.inf.ic]
  Lp.pos = L[pos.inf.ic + 1]
  Ap = Lp.pos - Lp
  Np.ant = if (pos.inf.ic > 1) tabla$Fr.cum.abs[pos.inf.ic - 1] else 0
  np = tabla$Fr.abs[pos.inf.ic]
  Q.p = Lp + Ap * ((p * n - Np.ant) / np)
  Q.p
}
```

La tabla de frecuencias de la longitud de los pétalos de **Iris** es:

```{r}
# Mediante el método de scott
p = 0.1
n = length(petals)
As = 3.5 * sd(petals) * n^(-1/3)
k = ceiling(diff(range(petals)) / As)
k
A = diff(range(petals)) / k
A
A = 1
TablaFrecs(petals, k, A, p)
```

```{r}
L = min(petals) - p/2 + A * (0:k)
TablaFrecs.L(petals, L, V = FALSE)
```

La tabla de frecuencias de la anchura de los **cangrejos** es:

```{r}
crabs = read.table("../../../../../Data/datacrab.txt", header = TRUE)
head(crabs, 5)
cw = crabs$width
```

```{r}
p = 0.1
n = length(cw)
n
As = 3.5 * sd(cw) * n^(-1/3)
k = ceiling(diff(range(cw)) / As)
k
A = diff(range(cw)) / k
A
A = 1.3
```

```{r}
TablaFrecs(cw, k, A, p)
```

```{r}
L = min(cw) - p/2 + A * (0:k)
tabla_cw = TablaFrecs.L(cw, L, V = FALSE)
tabla_cw
```

## Notas

```{r}
notas = c(6,0,3,3,8,2,7,9,10,0,8,3,1,10,4,5,10,6,10,8,7,10,5,
          5,7,9,5,9,5,5,6,2,9,7,5,10,5,6,4,0,10,2,6,1,9,0,9,  
          9,7,6,4,8,9,8,9,4,1,1,9,8,6,0,9,10,2,6,0,5,8,10,3,
          6,4,3,9,7,3,4,2,1,10,7,6,10,9,0,0,10,2,10,2,1,5,2,
          3,0,8,4,0,7)
notas
```

```{r}
L_notas = c(0,5,7,9,10)
notas.L = cut(notas, breaks = L_notas, right = FALSE, include.lowest = TRUE)
notas.L
```

```{r}
MC = (L_notas[1:length(L_notas) - 1] + L_notas[2:length(L_notas)]) / 2
notas.MC = cut(notas, breaks = L_notas, labels = MC, right = FALSE, include.lowest = TRUE)
notas.MC
```

```{r}
notas.O = cut(notas, breaks = L_notas, labels = FALSE, right = FALSE, include.lowest = TRUE)
notas.O
```

```{r}
notas.E = cut(notas, breaks = L_notas, labels = c("Susp", "Aprob", "Not", "Exc"), right = FALSE, include.lowest = TRUE)
notas.E
```

```{r}
table(notas.O)
prop.table(table(notas.E))
cumsum(table(notas.MC))
cumsum(prop.table(table(notas.E)))
```

```{r}
notasHist = hist(notas, breaks = L_notas, right = FALSE, include.lowest = TRUE, plot = FALSE)
notasHist
FAbs = notasHist$count
notasHist$count
FRel = prop.table(FAbs)
FAbsCum = cumsum(FAbs)
FRelCum = cumsum(FRel)
```

```{r}
intervalos = c("[0,5)", "[5,7)", "[7,9)", "[9,10]")
calificacion = c("Suspenso", "Aprobado", "Notable", "Excelente")
marcas = notasHist$mids
tabla.Fr = data.frame(intervalos, calificacion, marcas, FAbs, FAbsCum, FRel, FRelCum)
tabla.Fr
```

```{r}
tabla_notas = TablaFrecs.L(notas, L_notas, V = TRUE)
tabla_notas
```

## Estadísticos de datos agrupados para la anchura de los cangrejos

```{r}
n = tail(tabla_cw$Fr.cum.abs, 1)
n
```

```{r}
anchura.media = round(sum(tabla_cw$Fr.abs * tabla_cw$mc) / n, 3)
anchura.media
```

```{r}
anchura.var = round(sum(tabla_cw$Fr.abs * tabla_cw$mc^2) / n - anchura.media^2,3)
anchura.var
```

```{r}
anchura.var.muestral = round((n / (n-1)) * anchura.var,3)
anchura.var.muestral
```

```{r}
anchura.dt = round(sqrt(anchura.var),3)
anchura.dt
```

```{r}
anchura.dt.muestral = round(sqrt(anchura.var.muestral),3)
anchura.dt.muestral
```

```{r}
I.modal = tabla_cw$intervals[which(tabla_cw$Fr.abs == max(tabla_cw$Fr.abs))]
I.modal
```

```{r}
# Intervalo crítico para la mediana
I.critic = tabla_cw$intervals[which(tabla_cw$Fr.cum.rel >= 0.5)]
I.critic[1]
```

```{r}
quantile.aprox(tabla_cw, L, 4)
```

```{r}
median(cw)
```

```{r}
quantile.aprox(tabla_cw, L, 4, p = 0.25)
```

```{r}
quantile(cw, 0.25, names = FALSE)
```

```{r}
quantile.aprox(tabla_cw, L, 4, p = 0.75)
```

```{r}
quantile(cw, 0.75, names = FALSE)
```

## Estadísticos de datos agrupados para las notas

```{r}
n = tail(tabla_notas$Fr.cum.abs, 1)
n
```

```{r}
media.notas = round(sum(tabla_notas$Fr.abs * tabla_notas$mc) / n, 3)
media.notas
```

```{r}
var.notas = round(sum(tabla_notas$Fr.abs * tabla_notas$mc^2) / n - media.notas^2,3)
var.notas
```

```{r}
var.muestral.notas = round((n / (n-1)) * var.notas,3)
var.muestral.notas
```

```{r}
dt.notas = round(sqrt(var.notas),3)
dt.notas
```

```{r}
dt.muestral.notas = round(sqrt(var.muestral.notas),3)
dt.muestral.notas
```

```{r}
I.modal.notas = tabla_notas$intervals[which(tabla_notas$Fr.abs == max(tabla_notas$Fr.abs))]
I.modal.notas
```

```{r}
# Intervalo crítico para la mediana
I.critic = tabla_notas$intervals[which(tabla_notas$Fr.cum.rel >= 0.5)]
I.critic[1]
```

```{r}
quantile.aprox(tabla_notas, L_notas, 2)
```

```{r}
median(notas)
```

```{r}
quantile.aprox(tabla_notas, L_notas, 2, p = 0.25)
```

```{r}
quantile(notas, 0.25, names = FALSE)
```

```{r}
quantile.aprox(tabla_notas, L_notas, 2, p = 0.75)
```

```{r}
quantile(notas, 0.75, names = FALSE)
```
