---
title: "Relaciones"
author: "Martin Santamaria"
date: "14/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Relación Exponencial

```{r}
dep = c(1.2,3.6,12,36)
ind = c(20,35,61,82)
```

```{r fig.align='center'}
par(mfrow = c(1,2))
plot(ind, dep, main = "Esacala lineal")
plot(ind, dep, log = "y", main = "Escala semilogarítmica")
```

```{r}
lm(log10(dep)~ind)
```

```{r}
summary(lm(log10(dep)~ind))$r.squared
```

$$log(dep) = 0.023 \cdot ind - 0.33$$

Con lo cual

$$dep = 10^{0.023 \cdot ind} \cdot 10^{-0.33} = 1.054^{ind} \cdot 0.468$$
```{r fig.align='center'}
plot(ind, dep, main = "Curva de regresión")
curve(1.054^x*0.468, add = TRUE, col = "purple")
```

## Relación Potencial

```{r}
tiempo = 1:10
gramos = c(0.097,0.709,2.698,6.928,15.242,29.944,52.902,83.903,120.612,161.711)
d.f = data.frame(tiempo,gramos)
```

```{r fig.align='center'}
par(mfrow = c(1,3))
plot(d.f)
plot(d.f, log = "y")
plot(d.f, log = "xy")
```

```{r}
lm(log10(gramos)~log10(tiempo), data = d.f)
```

```{r}
summary(lm(log10(gramos)~log10(tiempo), data = d.f))$r.squared
```

$$log(gramos) = 3.298 \cdot log(tiempo) - 1.093$$

Con lo cual

$$gramos = 10^{3.298 \cdot log(tiempo)} \cdot 10^{-1.093} = tiempo^{3.298} \cdot 0.081$$

```{r}
plot(d.f, main = "Curva de regresión")
curve(x^(3.298)*0.081, add = TRUE, col = "purple")
```
