---
title: "Carga de DF"
author: "Martin Santamaria"
date: "3/2/2020"
output: html_document
---

# Carga de ficheros local

```{r}
df = read.table("../../../Data/bulls.dat",
                header = FALSE,
                col.names = c("breed", "sale_price", "shoulder",
                              "fat_free", "percent_ff", "frame_scale",
                              "back_fat", "sale_height", "sale_weight"),
                sep = "",
                dec = ".")
head(df)
```

# Carga desde URL

```{r}
df2 = read.table("https://maitra.public.iastate.edu/stat501/datasets/bulls.dat",
                 header = FALSE,
                 col.names = c("breed", "sale_price", "shoulder",
                               "fat_free", "percent_ff", "frame_scale",
                               "back_fat", "sale_height", "sale_weight"),
                 sep = "",
                 dec = ".")
head(df2)
str(df2)
```

# Factores en un DF

```{r}
#library(RCurl)
# df3 = read.table(textConnection(getURL("https://maitra.public.iastate.edu/stat501/datasets/olive.dat")),
#                  stringsAsFactors = FALSE,
#                  header = TRUE)
df3 = read.table("https://maitra.public.iastate.edu/stat501/datasets/olive.dat",
                 stringsAsFactors = FALSE,
                 header = TRUE)
str(df3)
```

# Guardar un DF

```{r}
write.table(df3, file = "../../../Data/olive.txt",
            dec = ".")
df4 = read.table("../../../Data/olive.txt",
                 header = TRUE,
                 dec = ".")
head(df4)
```

# Wine DF

```{r}
dfWine = read.table("https://maitra.public.iastate.edu/stat501/datasets/wine.dat",
                    stringsAsFactors = FALSE,
                    header = FALSE,
                    col.names = c("Cultivar","Alcohol","Malic_Acid","Ash","Ash_Alkalinity","Magnesium","Total_Phenols",
                                  "Flavanoids","Nonflavanoid_Phenols","Proanthocyanins","Color_Intensity","Hue","OD280_OD315_DW","Proline"),
                    sep = ",",
                    dec = ".")
str(dfWine)
write.table(dfWine, file = "../../../Data/wine.txt",
            sep = "  ")
```

# Crear un DF

```{r}
gender = c("H",  "M",  "H", "M",  "M")
age =    c( 31,   25,   37,  46,  31)
family = c(  0,    2,    1,   3,   1)
df5 = data.frame(Gen = gender, 
                 Age = age, 
                 Fam = family, 
                 stringsAsFactors = TRUE)
row.names(df5) = c("P1", "P2", "P3", "P4", "P5")
df5
dimnames(df5) = list(c("Antonio", "Maria", "Carlos", "Jesica", "Cinthia"),
                     c("Sexo", "Anios", "Miembros_Familia"))
df5
df5 = rbind(df5, c("H", 30, 1))
df5
df5$Sexo = as.character(df5$Sexo)
df5$Ingresos = c(10000, 12000, 15000, 12000, 20000, 14000)
row.names(df5)[nrow(df5)] = "Pablo"
df5
str(df5)
```


```{r}
gender = c("H",  "M",  "H", "M",  "M")
age =    c( 31,   25,   37,  46,  31)
family = c(  0,    2,    1,   3,   1)
df5 = data.frame(Gen = gender, 
                 Age = age, 
                 Fam = family, 
                 stringsAsFactors = TRUE)
df_m = df5[df5$Gen == "M",]
str(df_m)
df_m = droplevels(df_m)
str(df_m)
```


# Tidyverse

```{r}
library(tidyverse)
iris_petal <- select(iris, starts_with("Petal"))
head(iris_petal)
```

# Subset

```{r}
subset(iris, Species == "versicolor", select = c(1,3)) -> versicolor
row.names(versicolor) = 1:nrow(versicolor)
head(versicolor, 5)
str(versicolor)
```

```{r}
virginica <- subset(iris, Species == "virginica" & Sepal.Length < 7)
row.names(virginica) = 1:nrow(virginica)
head(virginica, 5)
```

```{r}
setosa <- subset(iris, Species == "setosa" & Sepal.Width > 2)
head(setosa, 5)
```

