---
title: "Código R & Python"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate
```{r, echo=FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
library(reticulate)
use_python("/Python38")
# py_install("")
# py_config()
os <- import("os")
os$listdir(".")
```

```{r add_py}
source_python("add.py")
add(3,4)
```

```{r import_numpy}
np <- import("numpy", convert = FALSE)
x <- np$array(c(1:4))
sum <- x$cumsum()

print(sum)

sum_r <- py_to_r(sum)
sum_r
```

```{r py_help}
# help("py_to_r")
# py_help(os$chdir)
```

```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```

```{python}
import numpy as np
import pandas as pd

r.datos_py.head()
```

## Sparse Matrix

```{r}
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N, N)
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

```{python}
r.sparse_mat_py
```

```{r}
py_to_r(sparse_mat_py)
```

$$\prod_{i=1}^n i$$







